on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install azd
        uses: Azure/setup-azd@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Log in with Azure
        run: |
          azd auth login \
            --client-id "$AZURE_CLIENT_ID" \
            --federated-credential-provider github \
            --tenant-id "$AZURE_TENANT_ID"
      
      - name: Create azd env
        run: azd env select prod || azd env new prod --no-prompt #azd env new prod --no-prompt
        working-directory: ./tools/AppHost

      - name: Set location
        run: azd env set AZURE_LOCATION $AZURE_LOCATION
        working-directory: ./tools/AppHost
        
      - name: Provision Infrastructure
        run: azd provision --no-prompt
        working-directory: ./tools/AppHost

      - name: Deploy
        run: azd deploy --no-prompt
        working-directory: ./tools/AppHost
